// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { type Options, PerformancesService, ResourcesService, UserRolesService } from '../sdk.gen';
import type { DeletePerformancesByIdData, DeletePerformancesByIdError, GetPerformancesByIdData, GetPerformancesByIdError, GetPerformancesByIdResourcesData, GetPerformancesByIdResourcesError, GetPerformancesByIdResourcesResponse, GetPerformancesByIdResponse, GetPerformancesData, GetPerformancesError, GetPerformancesResponse, GetResourcesByIdData, GetResourcesByIdError, GetResourcesByIdMetaData, GetResourcesByIdMetaError, GetResourcesByIdMetaResponse, GetResourcesByIdResponse, GetUserRolesData, GetUserRolesResponse, PostPerformancesByIdCoverData, PostPerformancesByIdResourcesData, PostPerformancesByIdResourcesResponse, PostPerformancesData, PostPerformancesError, PostPerformancesResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getPerformancesQueryKey = (options?: Options<GetPerformancesData>) => createQueryKey('getPerformances', options);

/**
 * Get all performances
 */
export const getPerformancesOptions = (options?: Options<GetPerformancesData>) => queryOptions<GetPerformancesResponse, AxiosError<GetPerformancesError>, GetPerformancesResponse, ReturnType<typeof getPerformancesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await PerformancesService.getPerformances({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPerformancesQueryKey(options)
});

/**
 * Create a new performance
 */
export const postPerformancesMutation = (options?: Partial<Options<PostPerformancesData>>): UseMutationOptions<PostPerformancesResponse, AxiosError<PostPerformancesError>, Options<PostPerformancesData>> => {
    const mutationOptions: UseMutationOptions<PostPerformancesResponse, AxiosError<PostPerformancesError>, Options<PostPerformancesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await PerformancesService.postPerformances({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a performances
 */
export const deletePerformancesByIdMutation = (options?: Partial<Options<DeletePerformancesByIdData>>): UseMutationOptions<unknown, AxiosError<DeletePerformancesByIdError>, Options<DeletePerformancesByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DeletePerformancesByIdError>, Options<DeletePerformancesByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await PerformancesService.deletePerformancesById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPerformancesByIdQueryKey = (options: Options<GetPerformancesByIdData>) => createQueryKey('getPerformancesById', options);

/**
 * Get performance by id
 */
export const getPerformancesByIdOptions = (options: Options<GetPerformancesByIdData>) => queryOptions<GetPerformancesByIdResponse, AxiosError<GetPerformancesByIdError>, GetPerformancesByIdResponse, ReturnType<typeof getPerformancesByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await PerformancesService.getPerformancesById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPerformancesByIdQueryKey(options)
});

/**
 * Set a cover for a performance
 */
export const postPerformancesByIdCoverMutation = (options?: Partial<Options<PostPerformancesByIdCoverData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostPerformancesByIdCoverData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostPerformancesByIdCoverData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await PerformancesService.postPerformancesByIdCover({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPerformancesByIdResourcesQueryKey = (options: Options<GetPerformancesByIdResourcesData>) => createQueryKey('getPerformancesByIdResources', options);

/**
 * Get all resources from a performance
 */
export const getPerformancesByIdResourcesOptions = (options: Options<GetPerformancesByIdResourcesData>) => queryOptions<GetPerformancesByIdResourcesResponse, AxiosError<GetPerformancesByIdResourcesError>, GetPerformancesByIdResourcesResponse, ReturnType<typeof getPerformancesByIdResourcesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await PerformancesService.getPerformancesByIdResources({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPerformancesByIdResourcesQueryKey(options)
});

/**
 * Create a new resource
 */
export const postPerformancesByIdResourcesMutation = (options?: Partial<Options<PostPerformancesByIdResourcesData>>): UseMutationOptions<PostPerformancesByIdResourcesResponse, AxiosError<DefaultError>, Options<PostPerformancesByIdResourcesData>> => {
    const mutationOptions: UseMutationOptions<PostPerformancesByIdResourcesResponse, AxiosError<DefaultError>, Options<PostPerformancesByIdResourcesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await PerformancesService.postPerformancesByIdResources({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getResourcesByIdQueryKey = (options: Options<GetResourcesByIdData>) => createQueryKey('getResourcesById', options);

/**
 * Get resource by id
 */
export const getResourcesByIdOptions = (options: Options<GetResourcesByIdData>) => queryOptions<GetResourcesByIdResponse, AxiosError<GetResourcesByIdError>, GetResourcesByIdResponse, ReturnType<typeof getResourcesByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ResourcesService.getResourcesById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getResourcesByIdQueryKey(options)
});

export const getResourcesByIdMetaQueryKey = (options: Options<GetResourcesByIdMetaData>) => createQueryKey('getResourcesByIdMeta', options);

/**
 * Get resource by id
 */
export const getResourcesByIdMetaOptions = (options: Options<GetResourcesByIdMetaData>) => queryOptions<GetResourcesByIdMetaResponse, AxiosError<GetResourcesByIdMetaError>, GetResourcesByIdMetaResponse, ReturnType<typeof getResourcesByIdMetaQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ResourcesService.getResourcesByIdMeta({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getResourcesByIdMetaQueryKey(options)
});

export const getUserRolesQueryKey = (options?: Options<GetUserRolesData>) => createQueryKey('getUserRoles', options);

/**
 * Get all user roles
 */
export const getUserRolesOptions = (options?: Options<GetUserRolesData>) => queryOptions<GetUserRolesResponse, AxiosError<DefaultError>, GetUserRolesResponse, ReturnType<typeof getUserRolesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await UserRolesService.getUserRoles({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserRolesQueryKey(options)
});
