monorepo_root = true

[monorepo]
config_roots = ["app", "backend"]
lockfile = true

[settings]
task_output = "prefix"
lockfile = true

[tools]
docker-cli = "29.6"

[tasks.backend-dependencies]
description = "Start backend dependencies"
run = "docker compose up -d"


[tasks.dev]
description = "Start project"
run = [
    { tasks = ["//backend:dev", "//app:dev"]}
]
