monorepo_root = true

[monorepo]
config_roots = ["app", "backend"]
lockfile = true

[settings]
task.output = "prefix"
lockfile = true

[tools]
docker-cli = "29.6"
prek = "0.5.2"

[tasks.backend-dependencies]
description = "Start backend dependencies"
run = "docker compose -f dev.compose.yml up -d"

[tasks."backend-dependencies:stop"]
description = "Stop backend dependencies"
run = "docker compose -f dev.compose.yml stop"

[tasks.dev]
description = "Start project"
run = [{ tasks = ["//backend:dev", "//app:dev"] }]
