// This file is auto-generated by @hey-api/openapi-ts

export const PerformanceSchema = {
    type: 'object',
    properties: {
        artist: {
            $ref: '#/definitions/model.Artist'
        },
        bpm: {
            type: 'integer'
        },
        cover: {
            $ref: '#/definitions/Resource'
        },
        createdAt: {
            type: 'string'
        },
        duration: {
            type: 'integer'
        },
        genres: {
            type: 'array',
            items: {
                $ref: '#/definitions/model.Genre'
            }
        },
        id: {
            type: 'string'
        },
        meter: {
            $ref: '#/definitions/model.Meter'
        },
        released: {
            type: 'integer'
        },
        resources: {
            type: 'array',
            items: {
                $ref: '#/definitions/Resource'
            }
        },
        titel: {
            type: 'string'
        },
        updatedAt: {
            type: 'string'
        }
    }
} as const;

export const ResourceSchema = {
    type: 'object',
    properties: {
        createdAt: {
            type: 'string'
        },
        filename: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        type: {
            type: 'string'
        },
        updatedAt: {
            type: 'string'
        },
        url: {
            type: 'string'
        },
        user_role: {
            $ref: '#/definitions/UserRole'
        }
    }
} as const;

export const UserRoleSchema = {
    type: 'object',
    properties: {
        createdAt: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        updatedAt: {
            type: 'string'
        }
    }
} as const;

export const main_ErrorResponseSchema = {
    type: 'object',
    properties: {
        error: {
            type: 'string'
        }
    }
} as const;

export const model_ArtistSchema = {
    type: 'object',
    properties: {
        createdAt: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        titel: {
            type: 'string'
        },
        updatedAt: {
            type: 'string'
        }
    }
} as const;

export const model_GenreSchema = {
    type: 'object',
    properties: {
        createdAt: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        titel: {
            type: 'string'
        },
        updatedAt: {
            type: 'string'
        }
    }
} as const;

export const model_MeterSchema = {
    type: 'object',
    properties: {
        createdAt: {
            type: 'string'
        },
        id: {
            type: 'string'
        },
        titel: {
            type: 'string'
        },
        updatedAt: {
            type: 'string'
        }
    }
} as const;
