// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeletePerformancesByIdData, DeletePerformancesByIdErrors, DeletePerformancesByIdResponses, GetPerformancesByIdData, GetPerformancesByIdErrors, GetPerformancesByIdResourcesData, GetPerformancesByIdResourcesErrors, GetPerformancesByIdResourcesResponses, GetPerformancesByIdResponses, GetPerformancesData, GetPerformancesErrors, GetPerformancesResponses, GetResourcesByIdData, GetResourcesByIdErrors, GetResourcesByIdMetaData, GetResourcesByIdMetaErrors, GetResourcesByIdMetaResponses, GetResourcesByIdResponses, GetUserRolesData, GetUserRolesErrors, GetUserRolesResponses, PostPerformancesByIdCoverData, PostPerformancesByIdCoverErrors, PostPerformancesByIdCoverResponses, PostPerformancesByIdResourcesData, PostPerformancesByIdResourcesErrors, PostPerformancesByIdResourcesResponses, PostPerformancesData, PostPerformancesErrors, PostPerformancesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class PerformancesService {
    /**
     * Get all performances
     */
    public static getPerformances<ThrowOnError extends boolean = false>(options?: Options<GetPerformancesData, ThrowOnError>): RequestResult<GetPerformancesResponses, GetPerformancesErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetPerformancesResponses, GetPerformancesErrors, ThrowOnError>({
            responseType: 'json',
            url: '/performances',
            ...options
        });
    }
    
    /**
     * Create a new performance
     */
    public static postPerformances<ThrowOnError extends boolean = false>(options: Options<PostPerformancesData, ThrowOnError>): RequestResult<PostPerformancesResponses, PostPerformancesErrors, ThrowOnError> {
        return (options.client ?? client).post<PostPerformancesResponses, PostPerformancesErrors, ThrowOnError>({
            ...formDataBodySerializer,
            responseType: 'json',
            url: '/performances',
            ...options,
            headers: {
                'Content-Type': null,
                ...options.headers
            }
        });
    }
    
    /**
     * Delete a performances
     */
    public static deletePerformancesById<ThrowOnError extends boolean = false>(options: Options<DeletePerformancesByIdData, ThrowOnError>): RequestResult<DeletePerformancesByIdResponses, DeletePerformancesByIdErrors, ThrowOnError> {
        return (options.client ?? client).delete<DeletePerformancesByIdResponses, DeletePerformancesByIdErrors, ThrowOnError>({
            responseType: 'json',
            url: '/performances/{id}',
            ...options
        });
    }
    
    /**
     * Get performance by id
     */
    public static getPerformancesById<ThrowOnError extends boolean = false>(options: Options<GetPerformancesByIdData, ThrowOnError>): RequestResult<GetPerformancesByIdResponses, GetPerformancesByIdErrors, ThrowOnError> {
        return (options.client ?? client).get<GetPerformancesByIdResponses, GetPerformancesByIdErrors, ThrowOnError>({
            responseType: 'json',
            url: '/performances/{id}',
            ...options
        });
    }
    
    /**
     * Set a cover for a performance
     */
    public static postPerformancesByIdCover<ThrowOnError extends boolean = false>(options: Options<PostPerformancesByIdCoverData, ThrowOnError>): RequestResult<PostPerformancesByIdCoverResponses, PostPerformancesByIdCoverErrors, ThrowOnError> {
        return (options.client ?? client).post<PostPerformancesByIdCoverResponses, PostPerformancesByIdCoverErrors, ThrowOnError>({
            ...formDataBodySerializer,
            responseType: 'json',
            url: '/performances/{id}/cover',
            ...options,
            headers: {
                'Content-Type': null,
                ...options.headers
            }
        });
    }
    
    /**
     * Get all resources from a performance
     */
    public static getPerformancesByIdResources<ThrowOnError extends boolean = false>(options: Options<GetPerformancesByIdResourcesData, ThrowOnError>): RequestResult<GetPerformancesByIdResourcesResponses, GetPerformancesByIdResourcesErrors, ThrowOnError> {
        return (options.client ?? client).get<GetPerformancesByIdResourcesResponses, GetPerformancesByIdResourcesErrors, ThrowOnError>({
            responseType: 'json',
            url: '/performances/{id}/resources',
            ...options
        });
    }
    
    /**
     * Create a new resource
     */
    public static postPerformancesByIdResources<ThrowOnError extends boolean = false>(options: Options<PostPerformancesByIdResourcesData, ThrowOnError>): RequestResult<PostPerformancesByIdResourcesResponses, PostPerformancesByIdResourcesErrors, ThrowOnError> {
        return (options.client ?? client).post<PostPerformancesByIdResourcesResponses, PostPerformancesByIdResourcesErrors, ThrowOnError>({
            ...formDataBodySerializer,
            responseType: 'json',
            url: '/performances/{id}/resources',
            ...options,
            headers: {
                'Content-Type': null,
                ...options.headers
            }
        });
    }
}

export class ResourcesService {
    /**
     * Get resource by id
     */
    public static getResourcesById<ThrowOnError extends boolean = false>(options: Options<GetResourcesByIdData, ThrowOnError>): RequestResult<GetResourcesByIdResponses, GetResourcesByIdErrors, ThrowOnError> {
        return (options.client ?? client).get<GetResourcesByIdResponses, GetResourcesByIdErrors, ThrowOnError>({
            responseType: 'blob',
            url: '/resources/{id}',
            ...options
        });
    }
    
    /**
     * Get resource by id
     */
    public static getResourcesByIdMeta<ThrowOnError extends boolean = false>(options: Options<GetResourcesByIdMetaData, ThrowOnError>): RequestResult<GetResourcesByIdMetaResponses, GetResourcesByIdMetaErrors, ThrowOnError> {
        return (options.client ?? client).get<GetResourcesByIdMetaResponses, GetResourcesByIdMetaErrors, ThrowOnError>({
            responseType: 'json',
            url: '/resources/{id}/meta',
            ...options
        });
    }
}

export class UserRolesService {
    /**
     * Get all user roles
     */
    public static getUserRoles<ThrowOnError extends boolean = false>(options?: Options<GetUserRolesData, ThrowOnError>): RequestResult<GetUserRolesResponses, GetUserRolesErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetUserRolesResponses, GetUserRolesErrors, ThrowOnError>({
            responseType: 'json',
            url: '/userRoles',
            ...options
        });
    }
}
