// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://10.2.0.2:8080/api/v1' | (string & {});
};

export type Performance = {
    bpm?: number;
    cover?: Resource;
    createdAt?: string;
    id?: string;
    name?: string;
    resources?: Array<Resource>;
    updatedAt?: string;
};

export type Resource = {
    createdAt?: string;
    filename?: string;
    id?: string;
    type?: string;
    updatedAt?: string;
    url?: string;
    user_role?: UserRole;
};

export type UserRole = {
    createdAt?: string;
    id?: string;
    name?: string;
    updatedAt?: string;
};

export type MainErrorResponse = {
    error?: string;
};

export type GetPerformancesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/performances';
};

export type GetPerformancesErrors = {
    /**
     * Internal Server Error
     */
    500: MainErrorResponse;
};

export type GetPerformancesError = GetPerformancesErrors[keyof GetPerformancesErrors];

export type GetPerformancesResponses = {
    /**
     * OK
     */
    200: Array<Performance>;
};

export type GetPerformancesResponse = GetPerformancesResponses[keyof GetPerformancesResponses];

export type PostPerformancesData = {
    body: {
        /**
         * Name
         */
        name: string;
        /**
         * Bpm
         */
        bpm?: number;
        /**
         * Album/Performance cover
         */
        cover?: Blob | File;
        /**
         * Upload file
         */
        file?: Blob | File;
        /**
         * Set user role
         */
        userRoleId?: string;
    };
    path?: never;
    query?: never;
    url: '/performances';
};

export type PostPerformancesErrors = {
    /**
     * Bad Request
     */
    400: MainErrorResponse;
    /**
     * Internal Server Error
     */
    500: MainErrorResponse;
};

export type PostPerformancesError = PostPerformancesErrors[keyof PostPerformancesErrors];

export type PostPerformancesResponses = {
    /**
     * Created
     */
    201: Performance;
};

export type PostPerformancesResponse = PostPerformancesResponses[keyof PostPerformancesResponses];

export type DeletePerformancesByIdData = {
    body?: never;
    path: {
        /**
         * Performance ID
         */
        id: string;
    };
    query?: never;
    url: '/performances/{id}';
};

export type DeletePerformancesByIdErrors = {
    /**
     * Not Found
     */
    404: MainErrorResponse;
    /**
     * Internal Server Error
     */
    500: MainErrorResponse;
};

export type DeletePerformancesByIdError = DeletePerformancesByIdErrors[keyof DeletePerformancesByIdErrors];

export type DeletePerformancesByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetPerformancesByIdData = {
    body?: never;
    path: {
        /**
         * Performance ID
         */
        id: string;
    };
    query?: never;
    url: '/performances/{id}';
};

export type GetPerformancesByIdErrors = {
    /**
     * Not Found
     */
    404: MainErrorResponse;
    /**
     * Internal Server Error
     */
    500: MainErrorResponse;
};

export type GetPerformancesByIdError = GetPerformancesByIdErrors[keyof GetPerformancesByIdErrors];

export type GetPerformancesByIdResponses = {
    /**
     * OK
     */
    200: Performance;
};

export type GetPerformancesByIdResponse = GetPerformancesByIdResponses[keyof GetPerformancesByIdResponses];

export type PostPerformancesByIdCoverData = {
    body: {
        /**
         * Album/Performance cover
         */
        cover: Blob | File;
    };
    path: {
        /**
         * Performance ID
         */
        id: string;
    };
    query?: never;
    url: '/performances/{id}/cover';
};

export type PostPerformancesByIdCoverErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostPerformancesByIdCoverResponses = {
    /**
     * No Content
     */
    201: unknown;
};

export type GetPerformancesByIdResourcesData = {
    body?: never;
    path: {
        /**
         * Performance ID
         */
        id: string;
    };
    query?: never;
    url: '/performances/{id}/resources';
};

export type GetPerformancesByIdResourcesErrors = {
    /**
     * Not Found
     */
    404: MainErrorResponse;
    /**
     * Internal Server Error
     */
    500: MainErrorResponse;
};

export type GetPerformancesByIdResourcesError = GetPerformancesByIdResourcesErrors[keyof GetPerformancesByIdResourcesErrors];

export type GetPerformancesByIdResourcesResponses = {
    /**
     * OK
     */
    200: Array<Resource>;
};

export type GetPerformancesByIdResourcesResponse = GetPerformancesByIdResourcesResponses[keyof GetPerformancesByIdResourcesResponses];

export type PostPerformancesByIdResourcesData = {
    body?: {
        /**
         * Role
         */
        role?: string;
        /**
         * Bild
         */
        resource?: Blob | File;
    };
    path: {
        /**
         * Performance ID
         */
        id: string;
    };
    query?: never;
    url: '/performances/{id}/resources';
};

export type PostPerformancesByIdResourcesErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostPerformancesByIdResourcesResponses = {
    /**
     * Created
     */
    201: Resource;
};

export type PostPerformancesByIdResourcesResponse = PostPerformancesByIdResourcesResponses[keyof PostPerformancesByIdResourcesResponses];

export type GetResourcesByIdData = {
    body?: never;
    path: {
        /**
         * Resource ID
         */
        id: string;
    };
    query?: never;
    url: '/resources/{id}';
};

export type GetResourcesByIdErrors = {
    /**
     * Not Found
     */
    404: MainErrorResponse;
    /**
     * Internal Server Error
     */
    500: MainErrorResponse;
};

export type GetResourcesByIdError = GetResourcesByIdErrors[keyof GetResourcesByIdErrors];

export type GetResourcesByIdResponses = {
    /**
     * Resource file
     */
    200: Blob | File;
};

export type GetResourcesByIdResponse = GetResourcesByIdResponses[keyof GetResourcesByIdResponses];

export type GetResourcesByIdMetaData = {
    body?: never;
    path: {
        /**
         * Resource ID
         */
        id: string;
    };
    query?: never;
    url: '/resources/{id}/meta';
};

export type GetResourcesByIdMetaErrors = {
    /**
     * Not Found
     */
    404: MainErrorResponse;
    /**
     * Internal Server Error
     */
    500: MainErrorResponse;
};

export type GetResourcesByIdMetaError = GetResourcesByIdMetaErrors[keyof GetResourcesByIdMetaErrors];

export type GetResourcesByIdMetaResponses = {
    /**
     * Resource Meta
     */
    200: Resource;
};

export type GetResourcesByIdMetaResponse = GetResourcesByIdMetaResponses[keyof GetResourcesByIdMetaResponses];

export type GetUserRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/userRoles';
};

export type GetUserRolesErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetUserRolesResponses = {
    /**
     * OK
     */
    200: Array<UserRole>;
};

export type GetUserRolesResponse = GetUserRolesResponses[keyof GetUserRolesResponses];
