// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zUserRole = z.object({
    createdAt: z.string().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    updatedAt: z.string().optional()
});

export const zResource = z.object({
    createdAt: z.string().optional(),
    filename: z.string().optional(),
    id: z.string().optional(),
    type: z.string().optional(),
    updatedAt: z.string().optional(),
    url: z.string().optional(),
    user_role: zUserRole.optional()
});

export const zPerformance = z.object({
    bpm: z.int().optional(),
    cover: zResource.optional(),
    createdAt: z.string().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    resources: z.array(zResource).optional(),
    updatedAt: z.string().optional()
});

export const zMainErrorResponse = z.object({
    error: z.string().optional()
});

export const zGetPerformancesQuery = z.object({
    desc: z.boolean().optional(),
    orderBy: z.string().optional()
});

/**
 * OK
 */
export const zGetPerformancesResponse = z.array(zPerformance);

export const zPostPerformancesBody = z.object({
    name: z.string().min(1).max(255),
    bpm: z.int().optional(),
    cover: z.string().optional(),
    file: z.string().optional(),
    userRoleId: z.uuid().optional()
});

/**
 * Created
 */
export const zPostPerformancesResponse = zPerformance;

export const zDeletePerformancesByIdPath = z.object({
    id: z.uuid()
});

export const zGetPerformancesByIdPath = z.object({
    id: z.uuid()
});

/**
 * OK
 */
export const zGetPerformancesByIdResponse = zPerformance;

export const zPostPerformancesByIdCoverBody = z.object({
    cover: z.string()
});

export const zPostPerformancesByIdCoverPath = z.object({
    id: z.uuid()
});

export const zGetPerformancesByIdResourcesPath = z.object({
    id: z.uuid()
});

/**
 * OK
 */
export const zGetPerformancesByIdResourcesResponse = z.array(zResource);

export const zPostPerformancesByIdResourcesBody = z.object({
    role: z.uuid().optional(),
    resource: z.string().optional()
});

export const zPostPerformancesByIdResourcesPath = z.object({
    id: z.uuid()
});

/**
 * Created
 */
export const zPostPerformancesByIdResourcesResponse = zResource;

export const zGetResourcesByIdPath = z.object({
    id: z.uuid()
});

/**
 * Resource file
 */
export const zGetResourcesByIdResponse = z.string();

export const zGetResourcesByIdMetaPath = z.object({
    id: z.uuid()
});

/**
 * Resource Meta
 */
export const zGetResourcesByIdMetaResponse = zResource;

/**
 * OK
 */
export const zGetUserRolesResponse = z.array(zUserRole);
