FROM node:24.21.0-alpine3.24@sha256:ebfe2f90462722a7a4de65e91990e97fe0d401c70e0e762c5b53302f905ec1c1 AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm npm ci --no-audit --no-fund --no-update-notifier

COPY --from=backend internal/docs/swagger.yaml ../backend/internal/docs/swagger.yaml

COPY . .

RUN --mount=type=cache,target=/tmp/metro-cache \
    npx tamagui generate \
    && npm run generate-client \
    && npx expo export --platform web

FROM nginxinc/nginx-unprivileged:stable-alpine-slim@sha256:e28dcf0a161ddcbf228c7364b4a14f9bad4763ae8f5317c437b896afa3df4b84

COPY nginx/bandmate7.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8080
