[tools]
node = "24.18"
npm = "12.0"

[env]
_.file = '.env'

[tasks.emulator]
description = "Start android emulator and wait until booted"
run = "ANDROID_EMULATOR_DEVICE=$ANDROID_EMULATOR_DEVICE sh ./scripts/start-android-emulator.sh"

[tasks.dev]
description = "Start frontend"
depends = ["emulator"]
run = "npm run android"

[tasks."dev:web"]
description = "Start frontend"
run = "npm run web"

[tasks.gen-client]
description = "Generate client"
run = "npm run generate-client"

[tasks.build-image]
description = "Build docker image"
run = "docker build -t bandMate7/web ."

[tasks."tamagui:gen"]
run = "npx tamagui generate"

[tasks."build:web"]
description = "Build web app"
depends = ["//app:tamagui:gen"]
run = "npx expo export --platform web"

[tasks."preview:web"]
description = "Preview the web app"
depends = ["//app:build:web"]
run = "npx serve dist"
