map $status $log_level {
    ~^5     error;
    ~^4     warn;
    default info;
}

log_format json escape=json
'{'
    '"timestamp": "$time_iso8601",'
    '"level": "$log_level",'
    '"pid": "$pid",'
    '"client_ip": "$remote_addr",'
    '"request_id": "$request_id",'
    '"http_method": "$request_method",'
    '"http_path": "$request_uri",'
    '"protocol": "$server_protocol",'
    '"host": "$host",'
    '"user_agent": "$http_user_agent",'
    '"referer": "$http_referer",'
    '"status_code": $status,'
    '"bytes_sent": $body_bytes_sent,'
    '"request_time_secs": $request_time'
'}';

server {
    listen 8080 default_server;
    listen [::]:8080;
    server_name _;

    access_log /var/log/nginx/access.log json;

    root  /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri.html $uri/index.html =404;
    }

    error_page 404 /+not-found.html;
}
